export const products = [
  {
    id: 1,
    name: 'X-Salada',
    price: 2000,
    category: 'Lanche',
  },
  {
    id: 2,
    name: 'X-Bacon',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 3,
    name: 'X-Calabresa',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 4,
    name: 'X-Bacon',
    price: 1200,
    category: 'Refrigerante',
  },
  {
    id: 1,
    name: 'X-Salada',
    price: 2000,
    category: 'Lanche',
  },
  {
    id: 2,
    name: 'X-Bacon',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 3,
    name: 'X-Calabresa',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 4,
    name: 'X-Bacon',
    price: 1200,
    category: 'Refrigerante',
  },
  {
    id: 1,
    name: 'X-Salada',
    price: 2000,
    category: 'Lanche',
  },
  {
    id: 2,
    name: 'X-Bacon',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 3,
    name: 'X-Calabresa',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 4,
    name: 'X-Bacon',
    price: 1200,
    category: 'Refrigerante',
  },
  {
    id: 1,
    name: 'X-Salada',
    price: 2000,
    category: 'Lanche',
  },
  {
    id: 2,
    name: 'X-Bacon',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 3,
    name: 'X-Calabresa',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 4,
    name: 'X-Bacon',
    price: 1200,
    category: 'Refrigerante',
  },
  {
    id: 1,
    name: 'X-Salada',
    price: 2000,
    category: 'Lanche',
  },
  {
    id: 2,
    name: 'X-Bacon',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 3,
    name: 'X-Calabresa',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 4,
    name: 'X-Bacon',
    price: 1200,
    category: 'Refrigerante',
  },
  {
    id: 1,
    name: 'X-Salada',
    price: 2000,
    category: 'Lanche',
  },
  {
    id: 2,
    name: 'X-Bacon',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 3,
    name: 'X-Calabresa',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 4,
    name: 'X-Bacon',
    price: 1200,
    category: 'Refrigerante',
  },
  {
    id: 1,
    name: 'X-Salada',
    price: 2000,
    category: 'Lanche',
  },
  {
    id: 2,
    name: 'X-Bacon',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 3,
    name: 'X-Calabresa',
    price: 2500,
    category: 'Lanche',
  },
  {
    id: 4,
    name: 'X-Bacon',
    price: 1200,
    category: 'Refrigerante',
  },
];
